name: 'Container Welcome'
input:
  welcome-intro:
    description: 'Hello'
    default: 'Everyone'
output:
  day:
    description: 'Today'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.welcome-intro }}

workflow_dispatch:
  inputs:
    environment:
      description: 'Environment to deploy to'
      type: environment
      required: true
